name = "kiss-worker"
main = "src/index.js"
compatibility_date = "2023-07-28"
kv_namespaces = [
    { binding = "KV", id = "5bad5cbc-0d9a-440f-a827-5515603c0939", preview_id = "01d3a47d26ca4732b4e6189b4d095ffe" }
]
